### ISSUE TITLE
Iteration control & using a 2nd or third <span>

### ISSUE THREAD

**Issue by DaleZki** [MrSaints/Morphext#12]
Great tooling leveraging Animate.CSS
~ ~
Using Animate.CSS I have been able to control iterations & delays; i.e.
animation-iteration-count: 1;
-webkit-animation-iteration-count: 1;
-ms-animation-iteration-count: 1;
Please direct me how to control these using Morphext
~ ~
with iterations set to "1"
How can use a second / third set of phases..?
I would use this when I where I would change the animated Class from, say, zoomIn to bounce

Thanks for your help......
~ ~ ~
as a reference I am trying to replicate the online FLASH version of an aninote.
 my edit... my name: http://dale.you.are.mighty.aninote.com/
 Aninote, main site reference: http://www.aninote.com/site.mpl?p=cont&cont=yam
 ~ ~ ~ .
 Thanks for this and any further ideas.....

D-

**Comment by MrSaints** [comment]
First, you shouldn't have to mess with `animation-iteration-count`. Morphext handles the animation loop, and by default, it goes on for infinity.

Second, I'm assuming you want a different animation class for each phrase. If that's the case, I believe the `complete` callback should be able to address your needs. It is fired after a phrase finishes animating in. For example:

```
$("#js-rotating").Morphext({
    animation: "rotateIn",
    complete: function () {
        if (this.index === 3) {
            this.settings.animation = "bounce";
        }
    }
});
```

The above will set the animation to "bounce" after the 3rd index is animated in. Thus, the 4th index will "bounce" in.

Third, I suggest you look into my other plugin if you'd like a bit more flexibility: https://github.com/MrSaints/Morphist

Let me know if that helps.

**Comment by DaleZki** [comment]
Thanks for taking the time for making the snippet and narrative.
This may very well do the trick.

While the loop is defaulted to infinity, does Morphext allow just one iteration?

Thanks again.

**Comment by MrSaints** [comment]
There's no built-in option for it, but it can be accomplished by using `complete()`. Example:

```js
$("#js-rotating").Morphext({
    complete: function () {
        // Stop at the last phrase
        if (this.index === this.phrases.length - 1) {
            this.stop();
        }
    }
});
```

**Comment by DaleZki** [comment]
wow... perfect..... I'll plug it in.
again... many thanks!
D-

**Comment by MrSaints** [comment]
No problem :smiley: I hope the plugin serves you well.

And do let me know if you require any further assistance. Always happy to help.

**Comment by sgkess** [comment]
> 
> 
> There's no built-in option for it, but it can be accomplished by using `complete()`. Example:
> 
> ```js
> $("#js-rotating").Morphext({
>     complete: function () {
>         // Stop at the last phrase
>         if (this.index === this.phrases.length - 1) {
>             this.stop();
>         }
>     }
> });
> ```

I tried applying this fix to your plugin, which is being used in the OnePress theme on wordpress.org, but for some reason nothing changes. I can only find your plugin in 2 spots in the editor, the plugins.js and the morphex.js files. I made the change in both, but still nothing. Any ideas? Thanks!

**Comment by MrSaints** [comment]
Hey @sgkess, do you have a live demo / small reproducible example I can look at ?

I'd suggest consulting the theme's support community or author, but happy to help in this case.

**Comment by sgkess** [comment]
> 
> 
> Hey @sgkess, do you have a live demo / small reproducible example I can look at ?
> 
> I'd suggest consulting the theme's support community or author, but happy to help in this case.

Here is the theme demo. I don't know if it will help. I appreciate you attempting to help anyway!

https://demos.famethemes.com/onepress/
