### ISSUE TITLE
Plugin removes HTML tags on words

### ISSUE THREAD

**Issue by dangelion** [MrSaints/Morphext#13]
I need to keep HTML tag on the words, ie:
```
I am a <span id="js-rotating">So Simple, <b>Very Doge</b>, <span class=""myclass>Much Wow</span>, Such Cool</span> Text Rotator
```
The plugin removes any HTML tags on the words. I know that probably this plugin is only for text (unformatted), but your plugin is awesome and the only thing I need is keeping html tags. Could you help me?

Thanks

Question solved:
How can I stop the rotate after it rotates all the words? I don't want a loop.

EDIT: solved with this https://github.com/MrSaints/Morphext/issues/12/#issuecomment-158661475

**Comment by MrSaints** [comment]
See my response here: https://github.com/MrSaints/Morphext/issues/1#issuecomment-167377808

If you're interested in changing it so it doesn't filter out HTML, look at: https://github.com/MrSaints/Morphext/blob/master/dist/morphext.js#L43

Change `text` to `html`.

Though, I don't intend on having this changed for Morphext.

Let me know if you need any further assistance or if you have any other questions :)
