### ISSUE TITLE
devDependencies out of date

### ISSUE THREAD

**Issue by Viltaria** [MrSaints/Morphext#16]

**Comment by MrSaints** [comment]
I'm a little tied up as of late, if you could submit a PR for this, I'm more than happy to have it merged in 👍

**Comment by Viltaria** [comment]
I submitted a pull request, could you take a look at it?

**Comment by MrSaints** [comment]
@Viltaria Will do.

**Comment by MrSaints** [comment]
Thanks a lot @Viltaria !
