### ISSUE TITLE
Add fadeInfadeOut stuff

### ISSUE THREAD

**Issue by nateGeorge** [MrSaints/Morphext#22]
Ideally what I'd like is fade in/fade out animations.  Right now I can only get it to fade in, and then it abruptly flashes out when it leaves.

**Comment by MrSaints** [comment]
Hi @nateGeorge, have you tried giving https://github.com/MrSaints/Morphist a shot? It's essentially the same thing, but with the described fade out animations as well.

**Comment by nateGeorge** [comment]
Hmm, I see, thanks.  The only problem is that after fadeout of one text and fade in of another, morphist is changing the height of something and the page awkwardly jumps a bit.  Maybe I'll open an issue on morphist for it.

**Comment by MrSaints** [comment]
@nateGeorge If you can set up a quick demo for me to have a look, I might be able to propose a quick fix (or address it if it is a bug) 😄 Thanks!

**Comment by nateGeorge** [comment]
Ok, making the demo and an issue on morphist now

**Comment by nateGeorge** [comment]
Hmm, well it seems with `display:inline-block;` for the <ul> and <br /> before and after the <ul>, the problem is gone.  Here's the demo I made for it though:  https://github.com/nateGeorge/morphist_bug_demo
