### ISSUE TITLE
Morphext is not a function

### ISSUE THREAD

**Issue by NikoGrano** [MrSaints/Morphext#29]
I cannot get Morphext function to loaded.

HTML is available here: https://pastebin.com/94mx9ZV1

14: Jquery Loaded.
16:Animate Loaded.
17:Morpheus Loaded.
97: Span.
136: Start of configuration. (Yes I know I have wrong ID on that paste. But even with right ID it's not working.)

Error Code:

internal-dev.ironlions.fi/:137 Uncaught TypeError: $(...).Morphext is not a function
    at internal-dev.ironlions.fi/:137
(anonymous)	@	internal-dev.ironlions.fi/:137

**Comment by NikoGrano** [comment]
Well, never mind. Might be time to go sleep. I was f using wrong js library. 

May I ask you to request JSCDN? 

https://github.com/cdnjs/cdnjs/issues/new?title=%5BRequest%5D%20Add%20rotator&body=**Library%20name%3A**%20rotator%0A**Git%20repository%20url%3A**%20%0A**npm%20package%20name%20or%20url**%20(if%20there%20is%20one)%3A%20%0A**License%20(List%20them%20all%20if%20it%27s%20multiple)%3A**%20%0A**Official%20homepage%3A**%20%0A**Wanna%20say%20something%3F%20Leave%20message%20here%3A**%20%0A%0A%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%0A%0ANotes%20from%20cdnjs%20maintainer%3A%0APlease%20read%20the%20%5BREADME.md%5D(https%3A%2F%2Fgithub.com%2Fcdnjs%2Fcdnjs%23cdnjs-library-repository)%20and%20%5BCONTRIBUTING.md%5D(https%3A%2F%2Fgithub.com%2Fcdnjs%2Fcdnjs%2Fblob%2Fmaster%2FCONTRIBUTING.md)%20document%20first.%0A%0AWe%20encourage%20you%20to%20add%20a%20library%20via%20sending%20pull%20request%2C%0Ait%27ll%20be%20faster%20than%20just%20opening%20a%20request%20issue%2C%0Asince%20there%20are%20tons%20of%20issues%2C%20please%20wait%20with%20patience%2C%0Aand%20please%20don%27t%20forget%20to%20read%20the%20guidelines%20for%20contributing%2C%20thanks!!%0A

**Comment by MrSaints** [comment]
@Niko9911 I believe it's pending action by CDNJS members: https://github.com/cdnjs/cdnjs/issues/9219
