### ISSUE TITLE
Typo in the instructions on morphext.fyianlai.com

### ISSUE THREAD

**Issue by lexoyo** [MrSaints/Morphext#34]
This is the first instruction you give on the website: `<script src="bower_components/Morphext/dist/morphext.min.js"><script>`

Notice the closing script tag is missing a `/`

**Comment by MrSaints** [comment]
Thanks for reporting this. I had several other people notify me about this.

Happy to accept a PR for it :)

**Comment by lexoyo** [comment]
I can do that sure :)
I just understood that the website repo is this one
