### ISSUE TITLE
Reset to first word upon click of a button

### ISSUE THREAD

**Issue by diarmuids** [MrSaints/Morphext#37]
Hi there,

I'm looking to reset Morphext back to the first word once a button is clicked - for example, this is the current jquery I'm using to initiate the animation. 

```
 $("#js-rotating").Morphext({
      animation: "fadeInUp",
      separator: ",",
      speed: 1200,
      complete: function () {}
    });

```
And I want to have another function such as

```
$(".hero-button").click(function(){
     (restart the morphext animation at the first word)
 });
```

Thanks in advance for your help!

**Comment by MrSaints** [comment]
Hey, give this a shot:

```js
var morphext = $("#js-rotating").Morphext({
     // ...
});
var data = morphext.data("plugin_Morphext");

$(".hero-button").click(function() {
    data.index = -1;
});
```

Bear in mind this won't stop the ongoing animation, and reset, it should in theory only restart the index so that the next word is the first one.

**Comment by diarmuids** [comment]
Thank you very very much - worked a treat!

Here's a jsfiddle of it
https://jsfiddle.net/diarmuids/cnhadvzb/

**Comment by diarmuids** [comment]
Actually, I was wondering is it possible to stop it and restart it on click - instantaneously? 

At present, it finishes the current animation and then goes back to the first word.

**Comment by diarmuids** [comment]
Got it!

```
$(".hero-button").click(function() {
    data.index = -1;
    data.stop ();
    data.animate ();
    data.start ()
});
```
JS Fiddle 
https://jsfiddle.net/diarmuids/cnhadvzb/
