### ISSUE TITLE
Help request safari buggy in front of video

### ISSUE THREAD

**Issue by Strutsagget** [MrSaints/Morphext#4]
Hi

Thanks for pointing me to your plugin.
Im having problem with safari and flipping text in front of a html 5 "background" video.

Don't think there is something wrong with the plugin just need to figure out why it happens.

www.pija.se

Working on smaller/compressing video so it might take  while before it starts. And flipping works until video starts.

**Comment by Strutsagget** [comment]
Solved it by removing z-index. Something must be wrong with safari and negative z-indexes.

**Comment by MrSaints** [comment]
I'm glad your problem is resolved, but do let me know if you have any other issues, concerns, suggestions, etc :) Awesome website by the way!
