### ISSUE TITLE
Listener events

### ISSUE THREAD

**Issue by karneaud** [MrSaints/Morphext#6]
Are there any events i can listen to?

**Comment by MrSaints** [comment]
@karneaud There is an event callback which you can pass your own function to. For example (taken from #3):

```js
$("#js-rotating").Morphext({
    complete: function () {
        // 1. Stop if phrase index is 3
        if (this.index === 3) {
            this.stop();
        }

        // 2. Stop if phrase is "Stop here" by retrieving the current phrase through its index
        if (this.phrases[this.index] === "Stop here") {
            this.stop();
        }

        // 3. Stop at the last phrase
        if (this.index === this.phrases.length - 1) {
            this.stop();
        }
    }
});
```

There's no specific pub/sub kind of event though. Let me know if this helps you and if not, let me know the specific event you would like and I may consider adding it in (or at least creating a modified version for you).

Thanks!

**Comment by MrSaints** [comment]
I'm closing this issue as it is becoming stale.

Please do let me know if you have any questions or other problems. I'm more than happy to help.
