### ISSUE TITLE
Compatibility with I.E < 8

### ISSUE THREAD

**Issue by eckoe** [MrSaints/Morphext#7]
It is not working wiht IE < 8, print that message:

Object doesn´t support this property or method
line: 44
character: 17

**Comment by MrSaints** [comment]
Hey, thanks for the report.

Unfortunately, I did not take IE < 10 into account seeing as the CSS3 animations which Animate.css uses is only compatible in IE 10+.

If the rotation / cycling isn't working, I'll look into that, but a fallback to a JavaScript-based solution will be needed if you wish to animate the individual objects (e.g. fade in) - see https://github.com/MrSaints/Morphext#issues for more information. 

Thanks again.

**Comment by morganisms** [comment]
I took .trim() out of this section of code and it fixed the error in ie8

b.phrases.push(c.trim())

**Comment by MrSaints** [comment]
Thanks for the discovery @morganisms. Does it work with:

`b.phrases.push($.trim(c));`
